alias safe_upgrade="sudo apt update && apt upgrade"
alias configure_nvim="vim ~/.config/nvim/init.vim"
alias configure_bash="vim ~/.bashrc"
alias env_activate_ISL="source /home/botan/.python_venvs/ISL/bin/activate"
alias ssh_ubuntu_server="ssh -p 2222 ubuntu@localhost"
